### ISSUE TITLE
Page Not Found - After Midtrans Payment Page

### ISSUE THREAD

**Issue by yosioliver** [veritrans/SNAP-Prestashop#15] opened 2019-08-29 10:16 UTC
Error occur because (amp; character on address browser bar)

https://my-url/index.php?fc=module&amp;module=midtranspay&amp;controller=success&amp;id_lang=2&order_id=26&status_code=200&transaction_status=capture.

When i removed the amp; then the order detail will appear as expected

PS : Prestashop 1.7.6.0
midtranspay plugin : downloaded from this github

Please advice....thank you

**Comment by rizdaprasetya** [comment] 2019-08-29 12:27
Try the current version, it should be fixed by https://github.com/veritrans/SNAP-Prestashop/pull/16
let us know if the issue still exist

**Closed** 2019-08-29 12:26 UTC

**Comment by yosioliver** [comment] 2019-08-30 09:43
![ss27](https://user-images.githubusercontent.com/6041203/64011004-021abf00-cb45-11e9-9d91-0ece77b15630.PNG)

Hi, Thank you for the response. But the problem still occurred. 

PS : 1. I already use the latest code from this github for the midtrans plugin
 2. Please see the image attached as the reference

Please advice, thank you

**Comment by rizdaprasetya** [comment] 2019-08-30 12:23
Looks like the issue is on your server/hosting configuration, or something is trying to encode HTML your frontend.

On our test environment and some other merchant server, we have not encounter such issue.

We can only attempt to fix, but no guarantee. Try again now with latest version.

If issue persist please check your server configuration.

**Comment by yosioliver** [comment] 2019-08-31 09:25
Hi,

Now the problem is resolved.

Thanks in advance :D


Regards,
